jobs:
  test:
    executor: go/default
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - run:
          command: |
            curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
            python get-pip.py
            pip install ansible
            wget --quiet https://releases.hashicorp.com/terraform/0.12.20/terraform_0.12.20_linux_amd64.zip
            sudo unzip terraform_0.12.20_linux_amd64.zip -d /usr/local/bin
          name: Install Terraform
      - go/test
orbs:
  go: circleci/go@0.2.0
  node: circleci/node@1.1.6
  gcp-cli: circleci/gcp-cli@1.8.4
version: 2.1
workflows:
  install_and_configure_cli:
    jobs:
      - gcp-cli/install_and_initialize_cli:
          context: gcp-ci-1
          executor: gcp-cli/default
          gcloud-service-key: GOOGLE_CREDENTIALS
  default:
    jobs:
      - test:
          context: gcp-ci-1
  version: 2
